apps/pastebin/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views


from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

from .views import SnippetViewSet, UserViewSet, api_root
from rest_framework import renderers
# from .views import snippet_list, snippet_detail
app_name = "pastebin"

# Create a router and register our viewsets with it.
# router = DefaultRouter()
# router.register(r'snippets', views.SnippetViewSet,basename="snippet")
# router.register(r'users', views.UserViewSet,basename="user")

# print(router.urls)
# # [<URLPattern '^snippets/$' [name='snippet-list']>, <URLPattern '^snippets\.(?P<format>[a-z0-9]+)/?$' [name='snippet-list']>, <URLPattern '^snippets/(?P<id>[^/.]+)/$' [name='snippet-detail']>, <URLPattern '^snippets/(?P<id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='snippet-detail']>, <URLPattern '^snippets/(?P<id>[^/.]+)/highlight/$' [name='snippet-highlight']>, <URLPattern '^snippets/(?P<id>[^/.]+)/highlight\.(?P<format>[a-z0-9]+)/?$' [name='snippet-highlight']>, <URLPattern '^$' [name='api-root']>, <URLPattern '^\.(?P<format>[a-z0-9]+)/?$' [name='api-root']>]

# # The API URLs are now determined automatically by the router.
# urlpatterns = [
#     path('', include(router.urls)),
# ]



snippet_list = SnippetViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

snippet_detail = SnippetViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

snippet_highlight = SnippetViewSet.as_view(
    {
        'get': 'highlight'
    },
    renderer_classes=[renderers.StaticHTMLRenderer]
)

user_list = UserViewSet.as_view({
    'get': 'list'
})
user_detail = UserViewSet.as_view({
    'get': 'retrieve'
})

# API endpoints


urlpatterns = [
    path('', api_root),
    path('snippets/', snippet_list, name='snippet-list'),
    path('snippets/<int:pk>/', snippet_detail, name='snippet-detail'),
    path('snippets/<int:pk>/highlight/', snippet_highlight, name='snippet-highlight'),
    path('users/', user_list, name='user-list'),
    path('users/<int:pk>/', user_detail, name='user-detail')
]

# urlpatterns = [
#     path('', views.api_root),
#     path(
#         'snippets/',
#         views.SnippetList.as_view(),
#         name='snippet-list'
#     ),
#     path(
#         'snippets/<int:pk>/', 
#         views.SnippetDetail.as_view(),
#         name='snippet-detail'
#     ),
#     path(
#         'snippets/<int:pk>/highlight/',
#         views.SnippetHighlight.as_view(),
#         name='snippet-highlight'
#     ),
#     path(
#         'users/',
#         views.UserList.as_view(),
#         name='user-list'
#     ),
#     path(
#         'users/<int:pk>/',
#         views.UserDetail.as_view(),
#         name='user-detail'
#     ),
# ]

# urlpatterns = [
#     # path('snippets/', views.snippet_list),
#     # path('snippets/<int:pk>/', views.snippet_detail),
#     path('', views.api_root),
#     path('snippets/', views.SnippetList.as_view()),
#     path('snippets/<int:pk>/', views.SnippetDetail.as_view()),
#     path('users/', views.UserList.as_view(),),
#     path('users/<int:pk>/', views.UserDetail.as_view()),
#     # path('users/', views.UserList.as_view()),
#     # path('users/<int:pk>/', views.UserDetail.as_view()),
#     # path('snippets/<int:pk>/highlight/', views.SnippetHighlight.as_view()),
# ]

urlpatterns = format_suffix_patterns(urlpatterns=urlpatterns, allowed=['json', 'html', 'csv'])

apps/polls/urls.py
from django.urls import path, re_path

from . import views
from . models import Passenger

# Namespace the url
# Name spacing allows the use of the {% url %} template tag across multiple apps
# See .html files where polls: tags the use of detail in the url template
app_name = "polls"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('ticket-class/', views.ticket_class_view, name='ticket_class'),
    path('ticket-class-2/', views.ticket_class_view_2, name='ticket_class_2'),
    path('ticket-class-3/', views.ticket_class_view_3, name='ticket_class_3'),    
    path('json-example/', views.json_example, name='json_example'),
    path('json-example/data/', views.chart_data, name='chart_data'),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    # path("graph/", views.graph, name='graph'),
    path("table-dt_basic/", views.view_datatable, name='table-dt_basic'),
    path("table-dt_basic-2/", views.PersonListView.as_view(), name='table-dt_basic-2'),
    path("table-dt_basic-3/", views.TablesView.as_view(), name='table-dt_basic-3'),
    path('tables/table_2/export/', views.TablesView.as_view()),    
    # re_path('^api/play_count_by_month', views.play_count_by_month, name='play_count_by_month'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

from django.urls import path, include
from core.serializers import PassengerViewSet
from rest_framework import routers




# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'passengers', PassengerViewSet)


urlpatterns = [
    path(route='admin/', view=admin.site.urls),          # Django admin route
    path(route="", view=include("apps.authentication.urls")), # Auth routes - login / register
    path('__debug__/', include('debug_toolbar.urls')),

    # ADD NEW Routes HERE
    path(route="polls/", view=include("apps.polls.urls")),
    path(route='pastebin/', view=include('apps.pastebin.urls')),
    # path('pastebin/', include(('apps.pastebin.urls', 'pastebin'), namespace='pastebin')),
    # path('api/', view=include('pastebin.urls', namespace='pastebin')),

    # If you're intending to use the browsable API you'll probably also want to add REST framework's login and logout views
    path('api/api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # TD test
    path('api/', include(router.urls)),


    # Leave `Home.Urls` as last the last line
    path(route="", view=include("apps.accounts.urls")),
    path(route="", view=include("apps.home.urls")),


]

apps/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    
class Play(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateTimeField()

    
from django.db import models

class Passenger(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    SEX_CHOICES = (
        (MALE, 'male'),
        (FEMALE, 'female')
    )

    CHERBOURG = 'C'
    QUEENSTOWN = 'Q'
    SOUTHAMPTON = 'S'
    PORT_CHOICES = (
        (CHERBOURG, 'Cherbourg'),
        (QUEENSTOWN, 'Queenstown'),
        (SOUTHAMPTON, 'Southampton'),
        ('nan', 'Unknown'),        
    )

    name = models.CharField(max_length=100, blank=True)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    survived = models.BooleanField()
    age = models.FloatField(null=True)
    ticket_class = models.PositiveSmallIntegerField()
    embarked = models.CharField(max_length=3, choices=PORT_CHOICES)

    def __str__(self):
        return self.name
    

class Person(models.Model):
    name = models.CharField(max_length=100, verbose_name="full name")    

apps/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

apps/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

apps/templates/polls/json_example.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Django Highcharts Example</title>
</head>
<body>
  <div id="container" data-url="{% url 'polls:chart_data' %}"></div>
  <script src="https://code.highcharts.com/highcharts.src.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $.ajax({
      url: $("#container").attr("data-url"),
      dataType: 'json',
      success: function (data) {
        Highcharts.chart("container", data);
      }
    });
  </script>
</body>
</html>

apps/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

apps/templates/polls/table-dt_basic-2.html
{% extends "layouts/base.html" %}
{% load render_table from django_tables2 %}

{% block title %} Tables DT Basic {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

    <!-- data tables css -->
    <link rel="stylesheet" href="{{ ASSETS_ROOT }}/css/plugins/dataTables.bootstrap5.min.css">

{% endblock stylesheets %}

{% block content %}	
    
<!-- [ Main Content ] start -->
<div class="pcoded-main-container">
    <div class="pcoded-wrapper">
        <div class="pcoded-content">
            <div class="pcoded-inner-content">
                <div class="main-body">
                    <div class="page-wrapper">
                        <!-- [ breadcrumb ] start -->
                        <div class="page-header">
                            <div class="page-block">
                                <div class="row align-items-center">
                                    <div class="col-md-12">
                                        <div class="page-header-title">
                                            <h5 class="m-b-10">Basic Initialization</h5>
                                        </div>
                                        <ul class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="/"><i
                                                        class="feather icon-home"></i></a></li>
                                            <li class="breadcrumb-item"><a href="#!">Data Table</a></li>
                                            <li class="breadcrumb-item">Basic Initialization</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- [ breadcrumb ] end -->
                        <!-- [ Main Content ] start -->
                        <div class="row">
                            <!-- Zero config table start -->
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>Zero Configuration</h5>
                                        <small>DataTables has most features enabled by default, so all you need to do to
                                            use it with your own tables is to call the construction function.</small>
                                    </div>
                                    <div class="card-body">
                                        <div class="dt-responsive table-responsive">
                                            {% render_table table %}
                                        </div>
                                    </div>
                                </div>
                            </div>                       
                            <!-- Zero config table end -->
                            <!-- Language - Comma Decimal Place table end -->
                        </div>
                        <!-- [ Main Content ] end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!-- datatable Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/jquery.dataTables.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/dataTables.bootstrap5.min.js"></script>
<script>
    // [ Zero Configuration ] start
    $('#simpletable').DataTable();

</script>

{% endblock javascripts %}

apps/templates/polls/table-dt_basic-3.html
{% extends "layouts/base.html" %}
{% load render_table from django_tables2 %}

{% block title %} Tables DT Basic {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

    <!-- data tables css -->
    <link rel="stylesheet" href="{{ ASSETS_ROOT }}/css/plugins/dataTables.bootstrap5.min.css">

{% endblock stylesheets %}

{% block content %}	
    
<!-- [ Main Content ] start -->
<div class="pcoded-main-container">
    <div class="pcoded-wrapper">
        <div class="pcoded-content">
            <div class="pcoded-inner-content">
                <div class="main-body">
                    <div class="page-wrapper">
                        <!-- [ breadcrumb ] start -->
                        <div class="page-header">
                            <div class="page-block">
                                <div class="row align-items-center">
                                    <div class="col-md-12">
                                        <div class="page-header-title">
                                            <h5 class="m-b-10">Basic Initialization</h5>
                                        </div>
                                        <ul class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="/"><i
                                                        class="feather icon-home"></i></a></li>
                                            <li class="breadcrumb-item"><a href="#!">Data Table</a></li>
                                            <li class="breadcrumb-item">Basic Initialization</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- [ breadcrumb ] end -->
                        <!-- [ Main Content ] start -->
                        <div class="row">
                            <!-- Zero config table start -->
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>Zero Configuration</h5>
                                        <small>DataTables has most features enabled by default, so all you need to do to
                                            use it with your own tables is to call the construction function.</small>
                                    </div>
                                    <div class="card-body">
                                        <div class="dt-responsive table-responsive">
                                            {% render_table table_1 %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                             <!-- Zero config table start -->
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>Titanic data</h5>
                                        <small>Data from the titanic model</small>
                                    </div>
                                    <div class="card-body">
                                        <div id="passenger-table" class="dt-responsive table-responsive">
                                            <style>
                                                #passenger-table {
                                                  height: 500px; /* Set the desired height for the container */
                                                  overflow: auto; /* Enable vertical scrolling */
                                                }
                                                
                                                #passenger-table table {
                                                  width: 100%; /* Ensure the table takes the full width of the container */
                                                  table-layout: fixed; /* Fix the table layout to prevent column width changes */
                                                }
                                                
                                                #passenger-table th {
                                                  position: sticky;
                                                  top: 0;
                                                  background-color: #fff; /* Set the background color of the sticky header */
                                                  z-index: 1; /* Ensure the header appears above the table content */
                                                }
                                                #passenger-table td {
                                                    white-space: normal;
                                                    word-wrap: break-word;
                                                  }
                                                {% comment %} .table-container td {
                                                    white-space: nowrap;
                                                    overflow: hidden;
                                                    text-overflow: ellipsis;
                                                } {% endcomment %}
                                            </style>
                                            {% render_table table_2 %}
                                            <a href="{{ model2_export_link }}" class="btn btn-primary">Export Model2 Table as CSV</a>
                                        </div>
                                    </div>
                                </div>
                            </div>                            
                            <!-- Zero config table end -->
                            <!-- Language - Comma Decimal Place table end -->
                        </div>
                        <!-- [ Main Content ] end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!-- datatable Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/jquery.dataTables.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/dataTables.bootstrap5.min.js"></script>
<script>
    // [ Zero Configuration ] start
    $('#simpletable').DataTable();

</script>

{% endblock javascripts %}

apps/templates/polls/table-dt_basic.html
{% extends "layouts/base.html" %}

{% block title %} Tables DT Basic {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

    <!-- data tables css -->
    <link rel="stylesheet" href="{{ ASSETS_ROOT }}/css/plugins/dataTables.bootstrap5.min.css">

{% endblock stylesheets %}

{% block content %}	
    
<!-- [ Main Content ] start -->
<div class="pcoded-main-container">
    <div class="pcoded-wrapper">
        <div class="pcoded-content">
            <div class="pcoded-inner-content">
                <div class="main-body">
                    <div class="page-wrapper">
                        <!-- [ breadcrumb ] start -->
                        <div class="page-header">
                            <div class="page-block">
                                <div class="row align-items-center">
                                    <div class="col-md-12">
                                        <div class="page-header-title">
                                            <h5 class="m-b-10">Basic Initialization</h5>
                                        </div>
                                        <ul class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="/"><i
                                                        class="feather icon-home"></i></a></li>
                                            <li class="breadcrumb-item"><a href="#!">Data Table</a></li>
                                            <li class="breadcrumb-item">Basic Initialization</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- [ breadcrumb ] end -->
                        <!-- [ Main Content ] start -->
                        <div class="row">
                            <!-- Zero config table start -->
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>Zero Configuration</h5>
                                        <small>DataTables has most features enabled by default, so all you need to do to
                                            use it with your own tables is to call the construction function.</small>
                                    </div>
                                    <div class="card-body">
                                        <div class="dt-responsive table-responsive">
                                            {% render_table table %}
                                            {% comment %} <table id="simpletable" class="table table-striped table-bordered nowrap">
                                                <thead>
                                                    <tr>
                                                        <th>Name</th>
                                                        <th>Position</th>
                                                        <th>Office</th>
                                                        <th>Age</th>
                                                        <th>Start date</th>
                                                        <th>Salary</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td>Quinn Flynn</td>
                                                        <td>System Architect</td>
                                                        <td>Edinburgh</td>
                                                        <td>61</td>
                                                        <td>2011/04/25</td>
                                                        <td>$320,800</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Garrett Winters</td>
                                                        <td>Accountant</td>
                                                        <td>Tokyo</td>
                                                        <td>63</td>
                                                        <td>2011/07/25</td>
                                                        <td>$170,750</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Ashton Cox</td>
                                                        <td>Junior Technical Author</td>
                                                        <td>San Francisco</td>
                                                        <td>66</td>
                                                        <td>2009/01/12</td>
                                                        <td>$86,000</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Cedric Kelly</td>
                                                        <td>Senior Javascript Developer</td>
                                                        <td>Edinburgh</td>
                                                        <td>22</td>
                                                        <td>2012/03/29</td>
                                                        <td>$433,060</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Airi Satou</td>
                                                        <td>Accountant</td>
                                                        <td>Tokyo</td>
                                                        <td>33</td>
                                                        <td>2008/11/28</td>
                                                        <td>$162,700</td>
                                                    </tr>

                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <th>Name</th>
                                                        <th>Position</th>
                                                        <th>Office</th>
                                                        <th>Age</th>
                                                        <th>Start date</th>
                                                        <th>Salary</th>
                                                    </tr>
                                                </tfoot>
                                            </table> {% endcomment %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Zero config table end -->
                            <!-- Language - Comma Decimal Place table end -->
                        </div>
                        <!-- [ Main Content ] end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!-- datatable Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/jquery.dataTables.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/dataTables.bootstrap5.min.js"></script>
<script>
    // [ Zero Configuration ] start
    $('#simpletable').DataTable();

</script>

{% endblock javascripts %}

apps/templates/polls/ticket_class.html
<div id="container"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
  Highcharts.chart('container', {
      chart: {
          type: 'column'
      },
      title: {
          text: 'Titanic Survivors by Ticket Class'
      },
      xAxis: {
          categories: [
            {% for entry in dataset %}'{{ entry.ticket_class }} Class'{% if not forloop.last %}, {% endif %}{% endfor %}
          ]
      },
      series: [{
          name: 'Survived',
          data: [
            {% for entry in dataset %}{{ entry.survived_count }}{% if not forloop.last %}, {% endif %}{% endfor %}
          ],
          color: 'green'
      }, {
          name: 'Not survived',
          data: [
            {% for entry in dataset %}{{ entry.not_survived_count }}{% if not forloop.last %}, {% endif %}{% endfor %}
          ],
          color: 'red'
      }]
  });
</script>

apps/templates/polls/ticket_class_2.html
<div id="container"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
  Highcharts.chart('container', {
      chart: {
          type: 'column'
      },
      title: {
          text: 'Titanic Survivors by Ticket Class'
      },
      xAxis: {
          categories: {{ categories|safe }}
      },
      series: [{
          name: 'Survived',
          data: {{ survived_series }},
          color: 'green'
      }, {
          name: 'Not survived',
          data: {{ not_survived_series }},
          color: 'red'
      }]
  });
</script>

apps/templates/polls/ticket_class_3.html
<div id="container"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
  Highcharts.chart('container', {{ chart|safe }});
</script>